language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
# does not have headers provided
# maintainers to fix their pypy-dev package
cache: pip
# command to install dependencies
before_install:
- sudo apt-get update
- sudo apt-get install python3
install:
- pip install -r requirements.txt
# command to run tests
script:
- python test_rpn.py
